### ISSUE TITLE
Big Sur downloads Catalina

### ISSUE THREAD

**Issue by flexage** [SpaceinvaderOne/Macinabox#33]
When selecting Big Sur as the Mac OS version to install, and leaving the download method as Method 1, the installer for Catalina is downloaded.

The Macinabox docker image in use is the latest, perhaps the Big Sur product ID has changed or something?

Download Method 2 just failed to do anything for me.

**Comment by flexage** [comment]
OK, got method 2 working by deleting the macinabox appdata, vm, and downloaded iso's.

Method 2 downloaded the correct version.

Tried method 1 twice and it downloaded Catalina both times.

**Comment by jack60612** [comment]
Happened to me too

**Comment by Maega** [comment]
Fixed in PR #37.
fetch.sh wasn't passing arguments onto fetch_macos.py when method 1 and Big Sur were selected.

**Comment by gloubix** [comment]
> OK, got method 2 working by deleting the macinabox appdata, vm, and downloaded iso's.
> 
> Method 2 downloaded the correct version.
> 
> Tried method 1 twice and it downloaded Catalina both times.

How did you delete the VM , i have this message ->

Requested operation is not valid: cannot undefine domain with nvram

**Comment by Cilusse** [comment]
> How did you delete the VM , i have this message ->
> 
> Requested operation is not valid: cannot undefine domain with nvram

You need to edit the VM in expert mode, and delete the line that defines the nvram location.
<nvram> something I think. It should be near the top third of the file.

**Comment by bpelech** [comment]
For everyone who ended up with Catalina instead of Big Sur, here's what I was able to gather and do to fix this issue:
1. Use method 2 as explained in the video from SpaceInvader (because this method expects downloading "InstallAssistant.pkg" which needs to be extracted).
2. Start Macinabox
3. Open console - click on Macinabox docker icon and then Console.
4. Install nano (or vim) - `apk add nano`
5. Edit unraid.sh - `nano /Macinabox/unraid.sh`. Find and replace `001-86606` to `071-05432` (this is correct big sur ID)
7. Restart Macinabox
8. Follow the SpaceInvader video

Additional troubleshooting:
- If you were too slow and wrong image was already downloaded while you were editing the unraid.sh no worries. Just delete the files from isos folder and restart Macinabox. It will download the correct files again.
- If you messed up somehow with the VM: delete the VM, restart the Macinabox and run the "1_macinabox_helper" user script again.
- If you can't delete the VM (I saw this error once "Requested operation is not valid: cannot delete inactive domain with nvram"), run this command from shell `virsh undefine --nvram "Macinabox BigSur"`. You can open the shell with the >_ icon from the right top corner.


Hope SpaceInvader will be able to find the time to fix the Macinabox. Until then - stay with catalina or try this fix.

If SpaceInvader will read this post: HUGE THANK YOU for this tool and all your work. You rock man! :-)
