### ISSUE TITLE
Permission denied on line 273 of /Macinabox/unraid.sh

### ISSUE THREAD

**Issue by TheManchineel** [SpaceinvaderOne/Macinabox#35]
I'm trying to install macOS Big Sur (using Method 2). I can see the storage space on the array going down as macOS is downloaded but suddenly it looks like the download is completely deleted and I just get this:
```
/Macinabox/unraid.sh: line 273: /Macinabox/tools/FetchMacOS/BaseSystem/SharedSupport.dmg: Permission denied
```

Looking at unraid.sh, lines 273 says:
```sh
rm /Macinabox/tools/FetchMacOS/BaseSystem/SharedSupport.dmg
```

**Comment by kprinssu** [comment]
The actual issue was fixed by https://github.com/SpaceinvaderOne/Macinabox/commit/35d62d523bc1c7ee3c6ec37abf3bf53c097e6f37

Before the above merge, the unraid script would attempted to run `/Macinabox/tools/FetchMacOS/BaseSystem/SharedSupport.dmg`. Since the filesystem didn't have the execute permission, the shell bailed with the Permission denied.

You have a couple of options, build the macinabox Docker image from scratch or wait for @SpaceinvaderOne to update the image on Docker Hub.

**Comment by homek1978** [comment]
You can also get to the console in Unraid, go to the /Macinabox directory, edit unraid sh by vi
vi unraid.sh
and comment out the offending line.
save and restart the docker container.
