### ISSUE TITLE
OpenCore Support + Docs

### ISSUE THREAD

**Issue by maxexcloo** [SpaceinvaderOne/Macinabox#9]
Hi,

I'm wondering if there will be any changes to OpenCore instead of Clover.

Also, is there anywhere I can see a list of all the tweaks and changes that had to be made to make this run? Would be cool to learn from it!

**Comment by extremeshok** [comment]
OpenCore would be much welcomed

**Comment by vtrikoupis** [comment]
+1 for opencore!

**Comment by chrisjenx** [comment]
Sorry for being dumb, what would OpenCore give us over Clover?

**Comment by vtrikoupis** [comment]
@chrisjenx please take a look at the first page [here ](https://dortania.github.io/OpenCore-Desktop-Guide/)

Greater control over what kext is being loaded, updating becomes painless etc etc

**Comment by chrisjenx** [comment]
Dang yeah, sounds great, esp AMD part. I mean it does run - but deffo not as smoothly as could be.

**Comment by Madd33n** [comment]
+1 for OC! Running my hack for about 4 months only with opencore. 
Best decision ever !!
Opencore ist lightweight, highly configurable and the developers don't dicing the installer on every update. 

Another big point for OC is, if i remember right, that acidanthera stopped to focus their tools (whatevergreen, Lilu, AppleALC) running on clover. Future focus only for the OC releases - which is logic because the also developed OC :)
